name: quiz_covid19_hackathon
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  auto_size_text: ^2.1.0
  http: ^0.12.0+4
  share: ^0.6.3+6
  flutter_launcher_icons: ^0.7.4
  translator: ^0.1.4
  step_progress_indicator: ^0.2.1+4
  flutter_native_splash: ^0.1.9
  devicelocale: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/icon_fg.png"
  image_path_ios: "assets/icon_fg.png"
  android: true 
  ios: true 
  adaptive_icon_background: "assets/icon_bg.png"
  adaptive_icon_foreground: "assets/icon_fg.png"

flutter_native_splash:
  image: assets/virus.png
  color: 2c3e50

flutter:
  uses-material-design: true
  assets:
    - assets/